apiVersion: v1
kind: Pod
metadata:
  name: testing
  namespace: minio
spec:
  containers:
  - command:
    - /bin/sh
    - -ce
    - sleep 10000
    env:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: accesskey
          name: minio-1683097766
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secretkey
          name: minio-1683097766
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    imagePullPolicy: IfNotPresent
    name: minio
    ports:
    - containerPort: 9000
      name: http
      protocol: TCP
    resources:
      requests:
        memory: 4Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /export
      name: export
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tqfqd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: h3-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  serviceAccount: minio-1683097766
  serviceAccountName: minio-1683097766
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: minio-1683097766
  - name: minio-user
    secret:
      defaultMode: 420
      secretName: minio-1683097766
  - name: kube-api-access-tqfqd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
